version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false  # 👈 Disable security for local setup
      - xpack.security.http.ssl.enabled=false  # 👈 Disable HTTPS requirement
    ports:
      - "9200:9200"
